---
title: "SQL assignment"
author: "Munan Hou"
date: "November 15, 2016"
output: html_document
---

```{r}
library(DBI)
library(RPostgreSQL)
```

```{r connect to the database}
host <- "analyticsga-east2.c20gkj5cvu3l.us-east-1.rds.amazonaws.com"
port <- "5432"
username <- "analytics_student"
password <- "analyticsga"

## Use the name of the specific database you will access
dbname <- "iowa_liquor_sales_database"

## Specify the PostreSQL driver
drv <- dbDriver("PostgreSQL")

## Now establish the connection
con <- dbConnect(drv, user = username, password = password, dbname = dbname, port = port, host = host)
```

```{r}
r3 <- dbGetQuery(con, statement = paste(
  "select case_cost",
  "from products"
  ))
head(r3)
```

```{r}
hist(x = as.vector(r3$case_cost), breaks = 100)
```

```{r statistical summary}
case_cost <- as.vector(as.numeric(r3$case_cost))
case_cost <- subset(case_cost, case_cost!=)
max(case_cost)
head(case_cost)
```

?subset

str(case_cost)

?hist

str(as.vector(r3$case_cost))
?summary

summary(as.vector(r3$case_cost))

r4 <-

```{r}
plot(as.vector(r3$case_cost), type = 'l', col='red')
points(as.vector(r3$case_cost), col='blue')
```












